INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Fabricação Própria');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Nacional');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Importado');
INSERT INTO TBL_CATEGORY (NAME)  VALUES ('Premium');

INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID, PROMOTION, NEW_PRODUCT)
VALUES ('Produto 01','Descrição do produto 01','100.5',2,true,false);

INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID, PROMOTION, NEW_PRODUCT)
VALUES ('Produto 02','Descrição do produto 02','200.5',1,true,true);

INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID, PROMOTION, NEW_PRODUCT)
VALUES ('Produto 03','Descrição do produto 03','300.5',3,false,false);

INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE, CATEGORY_ID, PROMOTION, NEW_PRODUCT)
VALUES ('Produto 04','Descrição do produto 04','4000.5',4,false,true);